---
- type: replace
  path: /instance_groups/name=docker/jobs/-
  value:
    name: cf-containers-shield-link
    release: dingo-redis-image
    consumes:
      shield-daemon:
        deployment: shield
        from: shield-daemon
    properties:
      cf:
        api_url: ((cf-api-url))
        admin_username: ((cf-admin-username))
        admin_password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))
