---
- type: replace
  path: /instance_groups/name=docker/jobs/-
  value:
    name: cf-containers-shield-link
    release: dingo-redis-image
    properties:
      shield-daemon:
        endpoint: ((shield-daemon-endpoint))
        provisioning_key: ((shield-daemon-provisioning-key))

- type: replace
  path: /instance_groups/-
  value:
    name: disaster-recovery
    lifecycle: errand
    azs: [z1]
    instances: 1
    vm_type: default
    stemcell: default
    networks: [{name: default}]
    jobs:
    - name: disaster-recovery
      release: dingo-redis-image
      consumes:
        servicebroker:
          from: broker
      properties:
        cf:
          api_url: ((cf-api-url))
          admin_username: ((cf-admin-username))
          admin_password: ((cf-admin-password))
          skip_ssl_validation: ((cf-skip-ssl-validation))
