---
- type: replace
  path: /instance_groups/name=docker/jobs/-
  value:
    name: cf-containers-shield-link
    release: dingo-redis-image
    consumes:
      shield-daemon:
        deployment: shield
        from: shield-daemon
