---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-redis-release-pipeline}

inputs:
- {name: boshrelease}
- {name: boshrelease-ci}

outputs:
- {name: final-release}

params:
  aws_access_key_id:
  aws_secret_access_key:
  bosh_target:
  bosh_username: admin
  bosh_password: admin

run:
  path: ./boshrelease-ci/ci/tasks/create-final-release.sh
  args: []
