---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-redis-release-pipeline}

inputs:
- name: boshrelease-ci

params:
  bosh_target:
  bosh_username: admin
  bosh_password: admin
  deployment_name:


run:
  path: boshrelease-ci/ci/tasks/delete-testflight.sh
