---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-redis-release-pipeline}

inputs:
- name: boshrelease-ci
- name: manifest

params:
  manifest: manifest/manifest.yml
  bosh_target:
  bosh_username:
  bosh_password:

run:
  path: ./boshrelease-ci/ci/tasks/show-broker-logs.sh
