---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-redis-release-pipeline}

inputs:
- name: boshrelease
- name: boshrelease-ci

params:
  bosh_target:
  bosh_username: admin
  bosh_password: admin

run:
  path: boshrelease-ci/ci/tasks/upload-dev-release.sh
