---
groups:
- name: images
  jobs: [image]

jobs:
- name: image
  public: true
  plan:
  - aggregate:
    - {get: docker-image-starkandwayne-redis, trigger: true}
    - {get: boshrelease-ci}
    - {get: boshrelease}
    - {get: version}
  - put: docker-image-dingotiles-redis
    params:
      dockerfile: boshrelease-ci/image

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: docker-image-starkandwayne-redis
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/redis
    tag: "latest"

- name: docker-image-dingotiles-redis
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-redis
    tag: "edge"

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.5.0
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: version
    file: version
    private_key: {{github-private-key}}
