---
groups:
- name: images
  jobs: [image, delmo]

jobs:
- name: image
  public: true
  plan:
  - aggregate:
    - {get: docker-image-starkandwayne-redis, trigger: true, params: {skip_download: true}}
    - {get: boshrelease-ci}
    - {get: boshrelease}
    - {get: version, params: {pre: rc}}
  - put: docker-image-dingotiles-redis
    params:
      build: boshrelease-ci/image

- name: delmo
  public: true
  plan:
  - aggregate:
    - {get: boshrelease-ci}
    - {get: boshrelease, passed: [image]}
    - {get: version, passed: [image], trigger: true}
  - task: run-delmo-test
    file: boshrelease-ci/ci/tasks/run-delmo-test.yml
    params:
      MACHINE_EXPORT_AWS_ACCESS_KEY_ID: {{docker-machine-access-key-id}}
      MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY: {{docker-machine-secret-access-key}}
      MACHINE_EXPORT_AWS_REGION: {{docker-machine-region}}
      MACHINE_EXPORT_AWS_BUCKET: {{docker-machine-bucket}}
      AWS_BUCKET: {{delmo-bucket}}
      AWS_REGION: {{delmo-aws-region}}
      AWS_ACCESS_KEY: {{delmo-aws-access}}
      AWS_SECRET_KEY: {{delmo-aws-secret}}

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: boshrelease-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: docker-image-starkandwayne-redis
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/redis
    tag: "latest"

- name: docker-image-dingotiles-redis
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-redis
    tag: "edge"

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.6.0
    uri: git@github.com:dingotiles/dingo-redis-image-boshrelease.git
    branch: version
    file: version
    private_key: {{github-private-key}}
