---
meta:
  name: dingo-redis-image
  target: sw
  url: https://ci.starkandwayne.com
  test-errands: sanity-test
  aws:
    access_key: (( vault "secret/pipelines/" meta.github.repo "/aws:access_key"))
    secret_key: (( vault "secret/pipelines/" meta.github.repo "/aws:secret_key"))
  github:
    owner: cloudfoundry-community
    repo: (( concat meta.name "-boshrelease" ))
    access_token: (( vault "secret/pipelines/" meta.github.repo "/github:access_token"))
    private_key:  (( vault "secret/pipelines/" meta.github.repo "/github:private_key"))
  bosh-lite:
    deployment: (( concat meta.name "-testflight" ))
    bosh_environment: (( vault "secret/bosh-lites/lite49" "/env:ip" ))
    bosh_ca_cert: (( vault "secret/bosh-lites/lite49" "/certs:rootCA.pem" ))
    bosh_client: admin
    bosh_client_secret: (( vault "secret/bosh-lites/lite49" "/users/admin:password" ))
    cf:
      api_url: (( vault "secret/bosh-lites/lite49" "/cf:api_url" ))
      system_domain: (( vault "secret/bosh-lites/lite49" "/cf:system_domain" ))
      username: (( vault "secret/bosh-lites/lite49" "/cf:admin_username" ))
      password: (( vault "secret/bosh-lites/lite49" "/cf:admin_password" ))
      skip_ssl_validation: (( vault "secret/bosh-lites/lite49" "/cf:skip_ssl_validation" ))
  slack:
    channel: Please specify the channel (#name) or user (@user) to send messages to
    webhook: Please specify your Slack Incoming Webhook Integration URL
